services:
  postgres:
  # https://www.baeldung.com/spring-boot-postgresql-docker
    image: postgres:13.1-alpine
    container_name: flights-postgres
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: flights
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qcuQJg3eM8B7z2WfDjCF6Y
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: