services:
  postgres:
  # https://www.baeldung.com/spring-boot-postgresql-docker
    image: postgres:13.1-alpine
    container_name: flights-postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flights-backend
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: flights-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - frontend-network
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: flights-proxy
    ports:
      - "80:80"
    networks:
      - backend-network
      - frontend-network
    depends_on:
      - backend
      - frontend

networks:
  frontend-network:
    driver: bridge
    name: frontend-network
  backend-network:
    driver: bridge
    name: backend-network

volumes:
  postgres-data: