/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CountryResponseDTO } from "./types";

import { axiosInstance } from "../lib/axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getCountryController = () => {
  const getCountries = (options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<CountryResponseDTO[]>({ url: `/api/countries`, method: "GET" }, options);
  };
  return { getCountries };
};
export type GetCountriesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getCountryController>["getCountries"]>>
>;
