/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type { CountryResponseDTO } from "./types";

export const getCountryController = () => {
  const getCountries = <TData = AxiosResponse<CountryResponseDTO[]>>(options?: AxiosRequestConfig): Promise<TData> => {
    return axios.get(`http://localhost:8080/api/countries`, options);
  };
  return { getCountries };
};
export type GetCountriesResult = AxiosResponse<CountryResponseDTO[]>;
