/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { FlightResponseDTO, GetFlightsParams, PagingResultFlightResponseDTO } from "./types";

import { axiosInstance } from "../lib/axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getFlightController = () => {
  const getFlights = (params?: GetFlightsParams, options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<PagingResultFlightResponseDTO>({ url: `/api/flights`, method: "GET", params }, options);
  };
  const getFlightById = (id: number, options?: SecondParameter<typeof axiosInstance>) => {
    return axiosInstance<FlightResponseDTO>({ url: `/api/flights/${id}`, method: "GET" }, options);
  };
  return { getFlights, getFlightById };
};
export type GetFlightsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFlightController>["getFlights"]>>>;
export type GetFlightByIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getFlightController>["getFlightById"]>>
>;
