/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface AirportResponseDTO {
  id?: number;
  name?: string;
  cityName?: string;
  countryName?: string;
}
