/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface BookingsResponseDTO {
  id?: number;
  seatId?: number;
  createdAt?: string;
}
