/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { GetFlightsDirection } from "./getFlightsDirection";

export type GetFlightsParams = {
  page?: number;
  size?: number;
  sortField?: string;
  direction?: GetFlightsDirection;
  departureAirport?: string;
  arrivalAirport?: string;
  departureCity?: string;
  arrivalCity?: string;
  departureCountry?: string;
  arrivalCountry?: string;
  departureTime?: string;
  arrivalTime?: string;
  searchTerm?: string;
  price?: number;
};
