/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetFlightsDirection = typeof GetFlightsDirection[keyof typeof GetFlightsDirection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetFlightsDirection = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
