/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SeatResponseDTO } from "./seatResponseDTO";

export interface PlaneResponseDTO {
  id?: number;
  name?: string;
  model?: string;
  seats?: SeatResponseDTO[];
}
