/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface SeatResponseDTO {
  id?: number;
  rowNumber?: number;
  columnLetter?: string;
  price?: number;
  SeatClass?: string;
  isWindow?: boolean;
  isAisle?: boolean;
  isExitRow?: boolean;
  isOccupied?: boolean;
}
